In [97]:
import pandas as pd

raw_data=pd.read_csv('Billionaires Statistics Dataset.csv')
df=pd.DataFrame(raw_data)

df.describe()

,rank,finalWorth,age,birthYear,birthMonth,birthDay,cpi_country,cpi_change_country,gross_tertiary_education_enrollment,gross_primary_education_enrollment_country,life_expectancy_country,tax_revenue_country_country,total_tax_rate_country,population_country,latitude_country,longitude_country
count,2640.000000,2640.000000,2575.000000,2564.000000,2564.000000,2564.000000,2456.000000,2456.000000,2458.000000,2459.000000,2458.000000,2457.000000,2458.000000,2.476000e+03,2476.000000,2476.000000
mean,1289.159091,4623.787879,65.140194,1957.183307,5.740250,12.099844,127.755204,4.364169,67.225671,102.858520,78.122823,12.546235,43.963344,5.102053e+08,34.903592,12.583156
std,739.693726,9834.240939,13.258098,13.282516,3.710085,9.918876,26.452951,3.623763,21.343426,4.710977,3.730099,5.368625,12.145296,5.542447e+08,17.003497,86.762989
min,1.000000,1000.000000,18.000000,1921.000000,1.000000,1.000000,99.550000,-1.900000,4.000000,84.700000,54.300000,0.100000,9.900000,3.801900e+04,-40.900557,-106.346771
25%,659.000000,1500.000000,56.000000,1948.000000,2.000000,1.000000,117.240000,1.700000,50.600000,100.200000,77.000000,9.600000,36.600000,6.683440e+07,35.861660,-95.712891
50%,1312.000000,2300.000000,65.000000,1957.000000,6.000000,11.000000,117.240000,2.900000,65.600000,101.800000,78.500000,9.600000,41.200000,3.282395e+08,37.090240,10.451526
75%,1905.000000,4200.000000,75.000000,1966.000000,9.000000,21.000000,125.080000,7.500000,88.200000,102.600000,80.900000,12.800000,59.100000,1.366418e+09,40.463667,104.195397
max,2540.000000,211000.000000,101.000000,2004.000000,12.000000,31.000000,288.570000,53.500000,136.600000,142.100000,84.200000,37.200000,106.300000,1.397715e+09,61.924110,174.885971

In [98]:
#Check for null values throghouut the dataset

for col in df.columns:
    NaNs = sum(df[col].isnull())
    if NaNs != 0:
        print(f'There are {NaNs} null values in column {col}.')
print('The other columns do not have null values.')

There are 65 null values in column age.
There are 38 null values in column country.
There are 72 null values in column city.
There are 2315 null values in column organization.
There are 76 null values in column birthDate.
There are 3 null values in column firstName.
There are 2301 null values in column title.
There are 1887 null values in column state.
There are 1893 null values in column residenceStateRegion.
There are 76 null values in column birthYear.
There are 76 null values in column birthMonth.
There are 76 null values in column birthDay.
There are 184 null values in column cpi_country.
There are 184 null values in column cpi_change_country.
There are 164 null values in column gdp_country.
There are 182 null values in column gross_tertiary_education_enrollment.
There are 181 null values in column gross_primary_education_enrollment_country.
There are 182 null values in column life_expectancy_country.
There are 183 null values in column tax_revenue_country_country.
There are 182 null values in column total_tax_rate_country.
There are 164 null values in column population_country.
There are 164 null values in column latitude_country.
There are 164 null values in column longitude_country.
The other columns do not have null values.

In [44]:
Restrict the dataset to 
# data['age'] = data['age'].apply(int)

In [151]:
#function that replaces null ages etc. with median age etc. 
#then converts to integer format

def null_int_med(df,col):
    df[df[col].isnull()] = df[df[col].notnull()][col].median()
    return df[col].apply(int)
    

df['age'] = null_int_med(df,'age')
df['birthYear'] = null_int_med(df,'birthYear')
df['birthMonth'] = null_int_med(df,'birthMonth')
df['birthDay'] = null_int_med(df,'birthDay')

df[['age','birthYear','birthMonth','birthDay']]
topten=df.sort_values(['age']).tail(10)
topten

,rank,finalWorth,category,personName,age,country,city,source,industries,countryOfCitizenship,...,cpi_change_country,gdp_country,gross_tertiary_education_enrollment,gross_primary_education_enrollment_country,life_expectancy_country,tax_revenue_country_country,total_tax_rate_country,population_country,latitude_country,longitude_country
1494,1957,1957,1957.0,1957.0,1957,1957.0,1957.0,1957.0,1957.0,1957.0,...,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0
2437,1957,1957,1957.0,1957.0,1957,1957.0,1957.0,1957.0,1957.0,1957.0,...,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0
2069,1957,1957,1957.0,1957.0,1957,1957.0,1957.0,1957.0,1957.0,1957.0,...,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0
2038,1957,1957,1957.0,1957.0,1957,1957.0,1957.0,1957.0,1957.0,1957.0,...,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0
902,1957,1957,1957.0,1957.0,1957,1957.0,1957.0,1957.0,1957.0,1957.0,...,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0
904,1957,1957,1957.0,1957.0,1957,1957.0,1957.0,1957.0,1957.0,1957.0,...,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0
1759,1957,1957,1957.0,1957.0,1957,1957.0,1957.0,1957.0,1957.0,1957.0,...,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0
913,1957,1957,1957.0,1957.0,1957,1957.0,1957.0,1957.0,1957.0,1957.0,...,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0
1809,1957,1957,1957.0,1957.0,1957,1957.0,1957.0,1957.0,1957.0,1957.0,...,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0
1592,1957,1957,1957.0,1957.0,1957,1957.0,1957.0,1957.0,1957.0,1957.0,...,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0,1957.0

In [110]:
full_name = lambda first, last: f'Full name: {first.title()} {last.title()}'
full_name('guido', 'van rossum')

'Full name: Guido Van Rossum'

In [130]:
def some_decorator(f):
    def wraps(*args):
        print(f"Calling function '{f.__name__}'")
        return f(args)
    return wraps

@some_decorator
def decorated_function(x):
    print(f"With argument '{x}'")

In [129]:
decorated_function(2)

Calling function 'decorated_function'
With argument '(2,)'

In [131]:
def average_age(members, gender):
   
  total_age = 0
  count = 0
   
  for member in members:
    name, age, member_gender = member
    
    if member_gender == gender:
      total_age += age
      count += 1
   
  if count > 0:
    average = total_age / count  
    return (average)
  else:
    return ('No matches found.')

In [156]:
def mult(x,y=2):
    return x*y**2

In [162]:
df.to_string()

"      rank  finalWorth                    category                                personName   age                   country                      city                               source                  industries  countryOfCitizenship                                    organization selfMade                status  gender        birthDate                     lastName                   firstName                                                         title           date                state residenceStateRegion  birthYear  birthMonth  birthDay  cpi_country  cpi_change_country           gdp_country  gross_tertiary_education_enrollment  gross_primary_education_enrollment_country  life_expectancy_country  tax_revenue_country_country  total_tax_rate_country  population_country  latitude_country  longitude_country\n0        1      211000            Fashion & Retail                  Bernard Arnault & family    74                    France                     Paris                                 LVMH            Fashion & Retail                France                LVMH Moët Hennessy Louis Vuitton    False                     U       M    3/5/1949 0:00                      Arnault                     Bernard                                              Chairman and CEO  4/4/2023 5:01                  NaN                  NaN       1949           3         5       110.05                 1.1   $2,715,518,274,227                                  65.6                                       102.5                     82.5                         24.2                    60.7        6.705989e+07         46.227638           2.213749\n1        2      180000                  Automotive                                 Elon Musk    51             United States                    Austin                        Tesla, SpaceX                  Automotive         United States                                           Tesla     True                     D       M   6/28/1971 0:00                         Musk                        Elon                                                           CEO  4/4/2023 5:01                Texas                South       1971           6        28       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n2        3      114000                  Technology                                Jeff Bezos    59             United States                    Medina                               Amazon                  Technology         United States                                          Amazon     True                     D       M   1/12/1964 0:00                        Bezos                        Jeff                                          Chairman and Founder  4/4/2023 5:01           Washington                 West       1964           1        12       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n3        4      107000                  Technology                             Larry Ellison    78             United States                     Lanai                               Oracle                  Technology         United States                                          Oracle     True                     U       M   8/17/1944 0:00                      Ellison                       Larry                                               CTO and Founder  4/4/2023 5:01               Hawaii                 West       1944           8        17       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n4        5      106000       Finance & Investments                            Warren Buffett    92             United States                     Omaha                   Berkshire Hathaway       Finance & Investments         United States                  Berkshire Hathaway Inc. (Cl A)     True                     D       M   8/30/1930 0:00                      Buffett                      Warren                                                           CEO  4/4/2023 5:01             Nebraska              Midwest       1930           8        30       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n5        6      104000                  Technology                                Bill Gates    67             United States                    Medina                            Microsoft                  Technology         United States                 Bill & Melinda Gates Foundation     True                     D       M  10/28/1955 0:00                        Gates                        Bill                                                       Cochair  4/4/2023 5:01           Washington                 West       1955          10        28       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n6        7       94500       Media & Entertainment                         Michael Bloomberg    81             United States                  New York                         Bloomberg LP       Media & Entertainment         United States                                       Bloomberg     True                     U       M   2/14/1942 0:00                    Bloomberg                     Michael                                                           CEO  4/4/2023 5:01             New York            Northeast       1942           2        14       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n7        8       93000                     Telecom                 Carlos Slim Helu & family    83                    Mexico               Mexico City                              Telecom                     Telecom                Mexico                                   América Móvil     True                     U       M   1/28/1940 0:00                    Slim Helu                      Carlos                                             Honorary Chairman  4/4/2023 5:01                  NaN                  NaN       1940           1        28       141.54                 3.6   $1,258,286,717,125                                  40.2                                       105.8                     75.0                         13.1                    55.1        1.260140e+08         23.634501        -102.552784\n8        9       83400                 Diversified                             Mukesh Ambani    65                     India                    Mumbai                          Diversified                 Diversified                 India                             Reliance Industries    False                     D       M   4/19/1957 0:00                       Ambani                      Mukesh                                          Founder and Chairman  4/4/2023 5:01                  NaN                  NaN       1957           4        19       180.44                 7.7   $2,611,000,000,000                                  28.1                                       113.0                     69.4                         11.2                    49.7        1.366418e+09         20.593684          78.962880\n9       10       80700                  Technology                             Steve Ballmer    67             United States               Hunts Point                            Microsoft                  Technology         United States                            Los Angeles Clippers     True                     D       M   3/24/1956 0:00                      Ballmer                       Steve                                                         Owner  4/4/2023 5:01           Washington                 West       1956           3        24       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n10      11       80500            Fashion & Retail     Francoise Bettencourt Meyers & family    69                    France                     Paris                              L'Oréal            Fashion & Retail                France                                             NaN    False                     U       F   7/10/1953 0:00           Bettencourt Meyers                   Francoise                                                           NaN  4/4/2023 5:01                  NaN                  NaN       1953           7        10       110.05                 1.1   $2,715,518,274,227                                  65.6                                       102.5                     82.5                         24.2                    60.7        6.705989e+07         46.227638           2.213749\n11      12       79200                  Technology                                Larry Page    50             United States                 Palo Alto                               Google                  Technology         United States                                        Alphabet     True                     D       M   3/26/1973 0:00                         Page                       Larry                                    Cofounder and board member  4/4/2023 5:01           California                 West       1973           3        26       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n12      13       77300            Fashion & Retail                            Amancio Ortega    87                     Spain                 La Coruna                                 Zara            Fashion & Retail                 Spain                                             NaN     True                     U       M   3/28/1936 0:00                       Ortega                     Amancio                                                           NaN  4/4/2023 5:01                  NaN                  NaN       1936           3        28       110.96                 0.7   $1,394,116,310,769                                  88.9                                       102.7                     83.3                         14.2                    47.0        4.707678e+07         40.463667          -3.749220\n13      14       76000                  Technology                               Sergey Brin    49             United States                 Los Altos                               Google                  Technology         United States                                        Alphabet     True                     D       M   8/21/1973 0:00                         Brin                      Sergey                                    Cofounder and board member  4/4/2023 5:01           California                 West       1973           8        21       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n14      15       68000             Food & Beverage                            Zhong Shanshan    68                     China                  Hangzhou           Beverages, pharmaceuticals             Food & Beverage                 China                                             NaN     True                     U       M   12/1/1954 0:00                        Zhong                    Shanshan                                                           NaN  4/4/2023 5:01                  NaN                  NaN       1954          12         1       125.08                 2.9  $19,910,000,000,000                                  50.6                                       100.2                     77.0                          9.4                    59.2        1.397715e+09         35.861660         104.195397\n15      16       64400                  Technology                           Mark Zuckerberg    38             United States                 Palo Alto                             Facebook                  Technology         United States                                  Meta Platforms     True                     D       M   5/14/1984 0:00                   Zuckerberg                        Mark                                                     Cofounder  4/4/2023 5:01           California                 West       1984           5        14       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n16      17       59000                 Diversified                     Charles Koch & family    87             United States                   Wichita                      Koch Industries                 Diversified         United States                           Koch Industries, Inc.    False                     D       M   11/1/1935 0:00                         Koch                     Charles                                              Chairman and CEO  4/4/2023 5:01               Kansas              Midwest       1935          11         1       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n17      17       59000                 Diversified                       Julia Koch & family    60             United States                  New York                      Koch Industries                 Diversified         United States                                             NaN    False                     D       F   4/12/1962 0:00                         Koch                       Julia                                                           NaN  4/4/2023 5:01             New York            Northeast       1962           4        12       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n18      19       58800            Fashion & Retail                                Jim Walton    74             United States               Bentonville                              Walmart            Fashion & Retail         United States                         Arvest Bank Group, Inc.    False                     D       M    6/7/1948 0:00                       Walton                         Jim                                              Chairman and CEO  4/4/2023 5:01             Arkansas                South       1948           6         7       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n19      20       57600            Fashion & Retail                       Rob Walton & family    78             United States               Bentonville                              Walmart            Fashion & Retail         United States                                         Walmart    False                     D       M  10/27/1944 0:00                       Walton                         Rob                                                      Director  4/4/2023 5:01             Arkansas                South       1944          10        27       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n20      21       56700            Fashion & Retail                              Alice Walton    73             United States                Fort Worth                              Walmart            Fashion & Retail         United States          Crystal Bridges Museum of American Art    False                     D       F   10/7/1949 0:00                       Walton                       Alice                                                Philanthropist  4/4/2023 5:01                Texas                South       1949          10         7       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n21      22       54400       Media & Entertainment                    David Thomson & family    65                    Canada                   Toronto                                Media       Media & Entertainment                Canada                     Thomson Reuters Corporation    False                     U       M   6/12/1957 0:00                      Thomson                       David                                                      Chairman  4/4/2023 5:01                  NaN                  NaN       1957           6        12       116.76                 1.9   $1,736,425,629,520                                  68.9                                       100.9                     81.9                         12.8                    24.5        3.699198e+07         56.130366        -106.346771\n22      23       50100                  Technology                              Michael Dell    58             United States                    Austin                    Dell Technologies                  Technology         United States                                       Dell Inc.     True                     D       M   2/23/1965 0:00                         Dell                     Michael                                              Chairman and CEO  4/4/2023 5:01                Texas                South       1965           2        23       117.24                 7.5  $21,427,700,000,000                                  88.2                                       101.8                     78.5                          9.6                    36.6        3.282395e+08         37.090240         -95.712891\n23      24       47200                 Diversified                              Gautam Adani    60                     India                 Ahmedabad          Infrastructure, commodities                 Diversified                 India          